# Generated by Django 5.0.6 on 2024-06-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteurs',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(blank=True, max_length=50, null=True)),
                ('Piece', models.CharField(blank=True, max_length=50, null=True)),
                ('Emplacement', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Capteur',
            },
        ),
        migrations.CreateModel(
            name='Donnees',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CapteurID', models.CharField(blank=True, max_length=50, null=True)),
                ('Timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('Valeur', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Donnees',
            },
        ),
    ]
