# Generated by Django 5.0.6 on 2024-06-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capteurs',
            old_name='Emplacement',
            new_name='Date',
        ),
    ]
