# Generated by Django 5.0.6 on 2024-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_emplacement_capteurs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteurs',
            name='Emplacement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
